In [70]:
#convinient compared to other packages
#Memory efficiency

#Speed(Numpy operations) > Speed(Lists operations)
#Size(Numpy operations) < Size(Lists operations)
#Memory optimization(Numpy) > Memory Optimization(List operations)

In [71]:
import numpy as np

In [72]:
#create a numpy array
#1D array

arr1D = np.array([1,2,3,4,5])
print(arr1D)

[1 2 3 4 5]


In [73]:
#creating 2D array - Matrix
arr2D=np.array([
    [1,2,3],[4,5,6]
    ])
print(arr2D)

[[1 2 3]
 [4 5 6]]


In [74]:
#Creating array with default values
allZeros = np.zeros((2,3))
print(allZeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [75]:
#Creating Matrix with all values of elements as "1"
allOnes = np.ones((2,3))
print(allOnes)

[[1. 1. 1.]
 [1. 1. 1.]]


In [76]:
#Creating Matrix with all values of elements 'constant value - n ~ Fill value'
allConstant = np.full((2,3),6)
print(allConstant)

[[6 6 6]
 [6 6 6]]


In [77]:
#Creating an indentity matrix - I - Square matrix
identityMatrix = np.eye(3)
print(identityMatrix)

#Identity Matrix - Aii=1 && aij=0
#For all A Belongs to R MxN
#Aij -

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [78]:
# Creating random Matrices
# with 0 and 1
rand1 = np.random.rand(3,3)
print(rand1)

[[0.89521884 0.52327387 0.94348862]
 [0.22948801 0.82968689 0.74165176]
 [0.72231133 0.81246985 0.446579  ]]


In [79]:
#between a and b
rand2 = np.random.randint(10,20,(3,3))
print(rand2)

[[13 10 11]
 [12 13 10]
 [18 18 15]]


In [80]:
# Array properties
arr = np.array([[1,2,3,4,5],[1,2,3,4,5]])
print(arr)

#Shape or array
print(arr.shape)

#Size of array
print(arr.size)

#Datatype of array
print(arr.dtype)

#Dimensions of array
print(arr.ndim)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)
10
int64
2


In [81]:
#Indexing and Slicing

#Access the elements in 1D Array
arr = np.array([1,2,3,4])
print(arr)
print(arr[3])

[1 2 3 4]
4


In [82]:
#Slicing the elements
print(arr[0:3])

[1 2 3]


In [83]:
#Access the elements in 2D array
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr2)
print(arr2[1,1])
print(arr2[0,:]) # first row with all columns
print(arr2[:,0]) # all columns with all rows

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
[1 2 3 4 5]
[1 6]


In [84]:
l1 = []
[l1.append(_) for _ in range(10)]
print(l1)

l1=np.arange(10,-10,-3)
print(l1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10  7  4  1 -2 -5 -8]


In [85]:
#Mathematical operations
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[4 6 8]
[-2 -2 -2]
[ 3  8 15]
[0.33333333 0.5        0.6       ]


In [86]:
#Matrix multiplication
b1 = np.array([[1,2,3],[2,3,4]])
b2 = np.array([[5,6],[7,8],[1,3]])

#Dot product --- product = AB -- A  mxn -- B nxp
c = np.dot(b1,b2)
print(c)

[[22 31]
 [35 48]]


In [87]:
print(b1)

[[1 2 3]
 [2 3 4]]


In [88]:
print(b2)

[[5 6]
 [7 8]
 [1 3]]
